# Generated by Django 4.2.30 on 2026-08-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectcategory_project_short_description_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-created_at'], name='project_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client', 'status', '-created_at'], name='project_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'budget'], name='project_status_budget_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbookmark',
            index=models.Index(fields=['user', '-created_at'], name='proj_bookmark_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdraft',
            index=models.Index(fields=['client', '-updated_at'], name='proj_draft_client_date_idx'),
        ),
        migrations.AddIndex(
            model_name='projectskill',
            index=models.Index(fields=['skill_name'], name='project_skill_name_idx'),
        ),
    ]
