# Generated by Django 4.2.30 on 2026-09-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_status_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approx_duration',
            field=models.CharField(blank=True, default='', help_text="Approximate time period for the project (e.g. '1-2 months')", max_length=50),
        ),
    ]
