# Generated by Django 4.2.30 on 2026-09-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_approx_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='approx_duration',
            field=models.CharField(help_text="Approximate time period for the project (e.g. '1-2 months')", max_length=50),
        ),
    ]
