# Generated by Django 4.2.30 on 2026-07-13 09:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worklogs', '0002_deliveryproof_approved_deliverables_and_more'),
        ('bidding', '0002_review_reviewresponse_contractterminationrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorklogApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklog_approvals', to=settings.AUTH_USER_MODEL)),
                ('worklog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='worklogs.worklog')),
            ],
            options={
                'db_table': 'worklog_approvals',
            },
        ),
        migrations.CreateModel(
            name='CounterOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proposed_deadline', models.DateField(blank=True, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_offers', to='bidding.bid')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_offers_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'counter_offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidRetraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('retracted_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retraction', to='bidding.bid')),
            ],
            options={
                'db_table': 'bid_retractions',
            },
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_type', models.CharField(choices=[('SCOPE_CHANGE', 'Scope Change'), ('BUDGET_CHANGE', 'Budget Change'), ('DEADLINE_CHANGE', 'Deadline Change'), ('COMBINED', 'Combined Changes')], max_length=20)),
                ('new_scope', models.TextField(blank=True, help_text='New scope description')),
                ('new_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('new_deadline', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Reason for amendment')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments_approved', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='bidding.contract')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments_proposed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contract_amendments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract', 'status'], name='contract_am_contrac_707b84_idx'), models.Index(fields=['proposed_by'], name='contract_am_propose_3bc46a_idx')],
            },
        ),
    ]
