# Generated by Django 4.2.30 on 2026-08-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_add_worklog_approval_bid_retraction_counter_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('PENDING_ACCEPTANCE', 'Pending Acceptance'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('TERMINATED', 'Terminated')], default='PENDING_ACCEPTANCE', max_length=30),
        ),
        migrations.AlterField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
