# Generated by Django 4.2.30 on 2026-08-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_contract_status_alter_contract_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('PENDING_ACCEPTANCE', 'Pending Acceptance'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=30),
        ),
    ]
