# Generated by Django 4.2.30 on 2026-08-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0005_alter_contract_is_active_alter_contract_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_reviewe_8697f0_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='review_rating_idx',
            old_name='reviews_rating_17e8a4_idx',
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['freelancer', 'status', '-created_at'], name='bid_freelancer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['project', 'status'], name='bid_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'is_active'], name='contract_status_active_idx'),
        ),
        migrations.AddIndex(
            model_name='counteroffer',
            index=models.Index(fields=['bid', 'status'], name='counter_bid_status_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewee', 'is_public', '-created_at'], name='review_reviewee_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer', '-created_at'], name='review_reviewer_created_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['contract'], name='review_contract_idx'),
        ),
    ]
