# Generated by Django 4.2.30 on 2026-09-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0006_remove_review_reviews_reviewe_8697f0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
