from django.db import models
from django.conf import settings
from apps.bidding.models import Contract


class AIConversation(models.Model):
    """
    Stores AI worklog assistant conversation history tied to a contract and freelancer.
    Message history is persisted as structured JSON objects for seamless state resumption.
    """
    contract = models.ForeignKey(
        Contract,
        on_delete=models.CASCADE,
        related_name="ai_conversations",
        db_index=True
    )
    freelancer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="ai_conversations",
        db_index=True
    )
    week_start = models.DateField(null=True, blank=True, db_index=True)
    week_end = models.DateField(null=True, blank=True)
    messages = models.JSONField(
        default=list,
        help_text="List of message objects: [{role: 'user'|'assistant'|'system', content: str, timestamp: str, metadata: dict}]"
    )
    is_active = models.BooleanField(default=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "ai_conversations"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["contract", "freelancer", "-created_at"], name="ai_conv_fl_date_idx"),
            models.Index(fields=["contract", "is_active"], name="ai_conv_active_idx"),
            models.Index(fields=["contract", "-created_at"], name="ai_conv_contract_date_idx"),
        ]

    def __str__(self):
        return f"AIConversation #{self.id} for Contract #{self.contract_id} ({self.freelancer.email})"


class AIReportDraft(models.Model):
    """
    Stores structured 3-section worklog report draft generated by the AI agent.
    Transitions from DRAFT to APPROVED when approved by the freelancer, compiling a WeasyPrint PDF.
    """
    class Status(models.TextChoices):
        DRAFT = "DRAFT", "Draft"
        APPROVED = "APPROVED", "Approved"
        REJECTED = "REJECTED", "Rejected"

    conversation = models.ForeignKey(
        AIConversation,
        on_delete=models.CASCADE,
        related_name="drafts",
        db_index=True
    )
    contract = models.ForeignKey(
        Contract,
        on_delete=models.CASCADE,
        related_name="ai_drafts",
        db_index=True
    )
    freelancer = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="ai_drafts",
        db_index=True
    )
    title = models.CharField(max_length=255, default="Weekly Progress Report")
    section_summary = models.TextField(
        blank=True,
        help_text="Executive summary of work accomplished during the period"
    )
    section_deliverables = models.JSONField(
        default=list,
        help_text="List of completed deliverables and key tasks [{title: str, description: str, status: str}]"
    )
    section_next_steps = models.TextField(
        blank=True,
        help_text="Next milestones, upcoming tasks, and blockers"
    )
    hours_worked = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        default=0.0,
        help_text="Total hours estimated or logged for this report period"
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.DRAFT,
        db_index=True
    )
    pdf_url = models.URLField(
        max_length=1000,
        blank=True,
        help_text="Azure Blob Storage SAS URL of compiled PDF report"
    )
    approved_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "ai_report_drafts"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["contract", "status", "-created_at"], name="ai_draft_contract_stat_idx"),
            models.Index(fields=["conversation", "-created_at"], name="ai_draft_conv_date_idx"),
            models.Index(fields=["freelancer", "status"], name="ai_draft_free_stat_idx"),
        ]

    def __str__(self):
        return f"AIReportDraft #{self.id}: {self.title} ({self.status}) for Contract #{self.contract_id}"


class QdrantCollection(models.Model):
    """
    Tracks Qdrant vector collection initialization and synchronization status per contract.
    Collection format: contract_{contract_id}_fl_{freelancer_id}
    """
    contract = models.OneToOneField(
        Contract,
        on_delete=models.CASCADE,
        related_name="qdrant_collection"
    )
    collection_name = models.CharField(
        max_length=120,
        unique=True,
        db_index=True
    )
    is_initialized = models.BooleanField(
        default=False,
        db_index=True
    )
    vectors_count = models.IntegerField(default=0)
    last_synced_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "qdrant_collections"
        ordering = ["-created_at"]

    def __str__(self):
        return f"QdrantCollection {self.collection_name} (initialized={self.is_initialized})"
