# Generated by Django 4.2.30 on 2026-07-29 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidding', '0003_add_worklog_approval_bid_retraction_counter_offer'),
        ('worklogs', '0003_add_worklog_approval_bid_retraction_counter_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreport',
            name='interval_days',
            field=models.IntegerField(default=7, help_text='Schedule interval that triggered this report (7, 14, or 30 days)'),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Azure Blob Storage SAS URL to generated PDF (7-day expiry)'),
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_days', models.IntegerField(choices=[(7, 'Every 7 days (Weekly)'), (14, 'Every 14 days (Biweekly)'), (30, 'Every 30 days (Monthly)')], default=7, help_text='How frequently to generate a progress report (7, 14, or 30 days)')),
                ('next_report_date', models.DateField(help_text='Date when the next progress report should be generated')),
                ('is_active', models.BooleanField(default=True, help_text='Pause/resume automatic report generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(help_text='The contract this schedule belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='report_schedule', to='bidding.contract')),
                ('created_by', models.ForeignKey(help_text='Client who configured this schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_schedules_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_schedules',
                'ordering': ['next_report_date'],
                'indexes': [models.Index(fields=['next_report_date', 'is_active'], name='report_sche_next_re_e2a13c_idx')],
            },
        ),
    ]
