# Generated by Django 4.2.30 on 2026-08-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0004_add_report_schedule'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deliverable',
            index=models.Index(fields=['contract', 'status', '-created_at'], name='deliverable_contract_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverable',
            index=models.Index(fields=['freelancer', 'status', '-created_at'], name='deliverable_free_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverable',
            index=models.Index(fields=['status', '-created_at'], name='deliverable_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='worklog',
            index=models.Index(fields=['freelancer', '-date'], name='worklog_freelancer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='worklog',
            index=models.Index(fields=['contract', 'status'], name='worklog_contract_status_idx'),
        ),
        migrations.AddIndex(
            model_name='worklog',
            index=models.Index(fields=['date'], name='worklog_date_idx'),
        ),
    ]
