# Generated by Django 4.2.30 on 2026-08-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0005_deliverable_deliverable_contract_stat_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryproof',
            name='pdf_url',
            field=models.URLField(help_text='Azure Blob Storage SAS URL to generated PDF'),
        ),
    ]
