# Generated by Django 4.2.30 on 2026-08-10 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bidding', '0006_remove_review_reviews_reviewe_8697f0_idx_and_more'),
        ('worklogs', '0005_deliverable_deliverable_contract_stat_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(blank=True, db_index=True, null=True)),
                ('week_end', models.DateField(blank=True, null=True)),
                ('messages', models.JSONField(default=list, help_text="List of message objects: [{role: 'user'|'assistant'|'system', content: str, timestamp: str, metadata: dict}]")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='bidding.contract')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='deliveryproof',
            name='pdf_url',
            field=models.URLField(help_text='Azure Blob Storage SAS URL to generated PDF'),
        ),
        migrations.CreateModel(
            name='QdrantCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('is_initialized', models.BooleanField(db_index=True, default=False)),
                ('vectors_count', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qdrant_collection', to='bidding.contract')),
            ],
            options={
                'db_table': 'qdrant_collections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIReportDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Weekly Progress Report', max_length=255)),
                ('section_summary', models.TextField(blank=True, help_text='Executive summary of work accomplished during the period')),
                ('section_deliverables', models.JSONField(default=list, help_text='List of completed deliverables and key tasks [{title: str, description: str, status: str}]')),
                ('section_next_steps', models.TextField(blank=True, help_text='Next milestones, upcoming tasks, and blockers')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0.0, help_text='Total hours estimated or logged for this report period', max_digits=6)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('pdf_url', models.URLField(blank=True, help_text='Azure Blob Storage SAS URL of compiled PDF report')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_drafts', to='bidding.contract')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='worklogs.aiconversation')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_report_drafts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract', 'status', '-created_at'], name='ai_draft_contract_stat_idx'), models.Index(fields=['conversation', '-created_at'], name='ai_draft_conv_date_idx'), models.Index(fields=['freelancer', 'status'], name='ai_draft_free_stat_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['contract', 'freelancer', '-created_at'], name='ai_conv_fl_date_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['contract', 'is_active'], name='ai_conv_active_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['contract', '-created_at'], name='ai_conv_contract_date_idx'),
        ),
    ]
