# Generated by Django 4.2.30 on 2026-08-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0006_aiconversation_alter_deliveryproof_pdf_url_and_more'),
        ('worklogs', '0006_alter_deliveryproof_pdf_url'),
    ]

    operations = [
    ]
