# Generated by Django 4.2.30 on 2026-09-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0007_merge_20260810_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Azure Blob Storage SAS URL to generated Deliverable PDF'),
        ),
    ]
