# Generated by Django 4.2.30 on 2026-09-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0008_deliverable_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aireportdraft',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Azure Blob Storage SAS URL of compiled PDF report', max_length=1000),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Azure Blob Storage SAS URL to generated Deliverable PDF', max_length=1000),
        ),
        migrations.AlterField(
            model_name='deliveryproof',
            name='pdf_url',
            field=models.URLField(help_text='Azure Blob Storage SAS URL to generated PDF', max_length=1000),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Azure Blob Storage SAS URL to generated PDF (7-day expiry)', max_length=1000),
        ),
    ]
