# Generated by Django 4.2.30 on 2026-08-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='searchhistory',
            new_name='search_hist_user_created_idx',
            old_name='search_hist_user_id_3ea0ad_idx',
        ),
        migrations.RenameIndex(
            model_name='searchsuggestion',
            new_name='search_sugg_term_idx',
            old_name='search_sugg_term_c6ad1c_idx',
        ),
        migrations.RenameIndex(
            model_name='searchsuggestion',
            new_name='search_sugg_pop_idx',
            old_name='search_sugg_popular_afaefb_idx',
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['user', 'is_active', '-created_at'], name='saved_search_user_act_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', 'search_type', '-created_at'], name='search_hist_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='searchsuggestion',
            index=models.Index(fields=['is_active', '-popularity'], name='search_sugg_active_pop_idx'),
        ),
    ]
