# Generated by Django 4.2.29 on 2026-06-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_payment_payout_error_payment_razorpay_payout_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrow",
            name="refund_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount refunded from escrow to client",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="razorpay_refund_id",
            field=models.CharField(
                blank=True, help_text="Razorpay Refund ID", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="refund_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount refunded to client (if any)",
                max_digits=12,
                null=True,
            ),
        ),
    ]
