# Generated by Django 4.2.30 on 2026-08-08 08:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_add_worklog_approval_bid_retraction_counter_offer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0006_add_refund_fields_to_payment_and_escrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiCurrencyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_currency', models.CharField(default='USD', max_length=3)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('converted_currency', models.CharField(default='USD', max_length=3)),
                ('converted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('conversion_date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multi_currency', to='payments.payment')),
            ],
            options={
                'db_table': 'multi_currency_payments',
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'currency_exchange_rates',
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
        migrations.CreateModel(
            name='TaxDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('1099', 'Form 1099'), ('W9', 'Form W-9'), ('OTHER', 'Other')], max_length=20)),
                ('tax_year', models.IntegerField()),
                ('total_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document_url', models.URLField(max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tax_documents',
                'ordering': ['-tax_year'],
                'unique_together': {('freelancer', 'tax_year', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='PaymentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage of total contract amount', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('order', models.IntegerField(default=1, help_text='Order of milestone in sequence')),
                ('deliverable_description', models.TextField(blank=True)),
                ('deliverable_files', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('client_feedback', models.TextField(blank=True)),
                ('payment_id', models.CharField(blank=True, max_length=255)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones_approved', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='bidding.contract')),
            ],
            options={
                'db_table': 'payment_milestones',
                'ordering': ['contract', 'order'],
                'indexes': [models.Index(fields=['contract', 'status'], name='payment_mil_contrac_fb37fe_idx'), models.Index(fields=['status'], name='payment_mil_status_844544_idx')],
                'unique_together': {('contract', 'order')},
            },
        ),
    ]
