# Generated by Django 4.2.30 on 2026-08-09 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_contract_status_alter_contract_is_active'),
        ('payments', '0007_multicurrencypayment_currencyexchangerate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='milestone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_record', to='payments.paymentmilestone'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bidding.contract'),
        ),
    ]
