# Generated by Django 4.2.30 on 2026-08-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_milestone_alter_payment_contract'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentmilestone',
            new_name='milestone_contract_stat_idx',
            old_name='payment_mil_contrac_fb37fe_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentmilestone',
            new_name='milestone_status_idx',
            old_name='payment_mil_status_844544_idx',
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['contract', 'status'], name='payment_contract_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_order_id'], name='payment_rzp_order_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['razorpay_payment_id'], name='payment_rzp_pay_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdispute',
            index=models.Index(fields=['disputer', 'status'], name='dispute_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdispute',
            index=models.Index(fields=['status', '-created_at'], name='dispute_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmilestone',
            index=models.Index(fields=['status', 'due_date'], name='milestone_stat_duedate_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmilestone',
            index=models.Index(fields=['contract', 'order'], name='milestone_contract_ord_idx'),
        ),
    ]
