# Generated by Django 4.2.30 on 2026-08-23 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0010_withdrawalrequest_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_wallets',
            },
        ),
        migrations.CreateModel(
            name='ClientDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, default='', max_length=255)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_fund_milestone', models.ForeignKey(blank=True, help_text='If set, this milestone will be funded automatically once deposit succeeds.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_deposits', to='payments.paymentmilestone')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_deposits',
                'ordering': ['-created_at'],
            },
        ),
    ]
