# Generated by Django 4.2.30 on 2026-08-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_freelancerprofile_address_freelancerprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='company_size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='is_onboarded',
            field=models.BooleanField(default=False, help_text='Whether client has completed initial onboarding'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='website',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
