# Generated by Django 4.2.30 on 2026-08-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_client_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='banner_image',
            field=models.URLField(blank=True, default='', help_text='Cover/banner image URL', max_length=500),
        ),
    ]
