# Generated by Django 4.2.30 on 2026-08-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_freelancer_banner_image'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='act_log_user_created_idx',
            old_name='activity_lo_user_id_b8c999_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='act_log_action_type_idx',
            old_name='activity_lo_action__9e4610_idx',
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'action_type', '-created_at'], name='act_log_user_action_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['subscription_tier', '-average_rating'], name='freelancer_tier_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['-total_earned'], name='freelancer_earned_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_deactivated'], name='user_role_active_idx'),
        ),
        migrations.AddIndex(
            model_name='useronlinestatus',
            index=models.Index(fields=['is_online', 'last_seen'], name='user_presence_idx'),
        ),
    ]
