# Generated by Django 4.2.30 on 2026-08-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_activity_lo_user_id_b8c999_idx_act_log_user_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='User email address has been verified'),
        ),
    ]
