# Generated by Django 4.2.30 on 2026-08-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='payout_account_holder',
            field=models.CharField(blank=True, default='', help_text='Account holder name for payouts', max_length=150),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='payout_bank_name',
            field=models.CharField(blank=True, default='', help_text='Bank name associated with payout account', max_length=100),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='payout_masked_account',
            field=models.CharField(blank=True, default='', help_text='Masked account number or UPI ID for display', max_length=50),
        ),
    ]
