# Generated by Django 4.2.30 on 2026-09-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_freelancerprofile_payout_account_holder_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='freelancerprofile',
            name='freelancer_tier_rating_idx',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='subscription_tier',
        ),
        migrations.AddIndex(
            model_name='freelancerprofile',
            index=models.Index(fields=['-average_rating'], name='freelancer_rating_idx'),
        ),
    ]
