# Generated by Django 4.2.30 on 2026-09-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_freelancerprofile_freelancer_tier_rating_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
