# Generated by Django 4.2.30 on 2026-09-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_clientprofile_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('FREELANCER', 'Freelancer'), ('ADMIN', 'Admin')], default='FREELANCER', max_length=20),
        ),
    ]
