# Generated by Django 4.2.30 on 2026-08-08 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('BID_SUBMITTED', 'Bid Submitted'), ('BID_ACCEPTED', 'Bid Accepted'), ('ESCROW_CREATED', 'Escrow Created'), ('LOG_SUBMITTED', 'Log Submitted'), ('REPORT_READY', 'Report Ready'), ('REPORT_UPCOMING', 'Report Due Soon'), ('CLIENT_REPORT_READY', 'Client: New Report Available'), ('PAYMENT_RELEASED', 'Payment Released'), ('PROOF_READY', 'Proof Ready'), ('MESSAGE_RECEIVED', 'Message Received')], max_length=50),
        ),
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('announcement_type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('MAINTENANCE', 'Maintenance'), ('FEATURE', 'New Feature')], default='INFO', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('target_users', models.CharField(choices=[('all', 'All Users'), ('freelancers', 'Freelancers Only'), ('clients', 'Clients Only')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_announcements',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_bid_received', models.BooleanField(default=True)),
                ('email_bid_accepted', models.BooleanField(default=True)),
                ('email_payment_released', models.BooleanField(default=True)),
                ('email_deliverable_submitted', models.BooleanField(default=True)),
                ('email_review_received', models.BooleanField(default=True)),
                ('email_contract_termination', models.BooleanField(default=True)),
                ('email_dispute', models.BooleanField(default=True)),
                ('email_message', models.BooleanField(default=True)),
                ('push_bid_received', models.BooleanField(default=True)),
                ('push_bid_accepted', models.BooleanField(default=True)),
                ('push_payment_released', models.BooleanField(default=True)),
                ('push_deliverable_submitted', models.BooleanField(default=True)),
                ('push_review_received', models.BooleanField(default=True)),
                ('push_contract_termination', models.BooleanField(default=True)),
                ('push_dispute', models.BooleanField(default=True)),
                ('push_message', models.BooleanField(default=True)),
                ('inapp_all', models.BooleanField(default=True)),
                ('weekly_digest', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='DigestEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'digest_emails',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_data', models.JSONField(help_text='Push subscription info from browser')),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'push_subscriptions',
                'unique_together': {('user', 'subscription_data')},
            },
        ),
    ]
