# Generated by Django 4.2.30 on 2026-08-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type_systemannouncement_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notif_recipient_is_read_idx',
            old_name='notificatio_recipie_583549_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_recip_read_date_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notif_recip_created_idx'),
        ),
        migrations.AddIndex(
            model_name='systemannouncement',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='announcement_active_wind_idx'),
        ),
    ]
